config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :exams
    resources :users
    resources :tasks
    resources :groups do
      resources :students, only: [:index, :create, :destroy] do
        put :update_number, on: :collection
      end
    end
  end

  namespace :exam do
    resources :groups
    resources :students do
      resources :tasks
    end
  end

  namespace :reports do
    resources :groups, only: [:index, :show]
  end

  resources :exams, only: [] do
    put :set_current, on: :member
  end

  root 'exam/groups#index'
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :students, through: :groups
  has_many :subtasks, through: :tasks

  validates :name, presence: true, uniqueness: true

  def to_s
    name
  end
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < Admin::BaseController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def create
    if @exam.save
      redirect_to admin_exams_path, notice: t('.exam_created')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @exam.update(exam_params)
      redirect_to edit_admin_exam_path(@exam), notice: t('.exam_updated')
    else
      render :edit
    end
  end

  def destroy
    @exam.destroy
    redirect_to admin_exams_path, notice: t('.exam_destroyed')
  end

  private

  def exam_params
    params.require(:exam).permit(:name)
  end
end

app/controllers/exam/base_controller.rb
class Exam::BaseController < BaseController
end

app/controllers/exam/groups_controller.rb
class Exam::GroupsController < Exam::BaseController
  load_and_authorize_resource through: :current_exam

  def index
  end

  def edit
  end

  def update
  end

  def show
    @tasks = @group.tasks
  end
end

app/controllers/exam/tasks_controller.rb
class Exam::TasksController < Exam::BaseController
  load_and_authorize_resource :student, through: :current_exam
  load_and_authorize_resource through: :student

  def edit
    @scores = @task.scores.where(student: @student).ordered
  end

  def update
    @scores = Score.update(params[:scores].keys, params[:scores].values)
    @scores.reject! { |s| s.errors.empty? }

    if @scores.empty?
      next_task = @student.tasks.where(level: @task.level).where('tasks.number > ?', @task.number).first || @student.tasks.where(level: @task.level).where('tasks.number >= ? AND tasks.secondary_number > ?', @task.number, @task.secondary_number).first
      
      if next_task
        redirect_to edit_exam_student_task_url(@student, next_task)
      else
        task_level = @task.level != 'standard' ? @task.level : nil
        redirect_to edit_exam_group_url(@student.group, group_type: task_level), notice: t('.score_updated')
      end
    else
      render :edit
    end
  end
end

app/controllers/exams_controller.rb
class ExamsController < BaseController
  load_and_authorize_resource

  def set_current
    set_current_exam(@exam.id)
    redirect_to root_path, notice: t('custom_messages.exam_changed', exam: @exam.name)
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
  def current_exam
    @current_exam ||= Exam.find_by(id: current_exam_id) || Exam.first
  end

  def set_current_exam(id)
    cookies.signed[:current_exam] = id
    # flash.notice = t('flash.custom.current_plant_set', exam: current_exam)
  end

  def current_exam_id
    if can? :set_current, Exam
      cookies.signed[:current_exam]
    else
      Exam.first.id
    end
  end

  def available_exams
    Exam.all
  end
end

app/views/admin/exams/_form.html.haml
.col-4
  = simple_form_for [:admin, @exam] do |f|
    = f.input :name

    = f.submit t('save'), class: 'btn btn-info'

app/views/admin/exams/_form.html.slim
.col-4
  = simple_form_for [:admin, @exam] do |f|
    = f.input :name

    = f.submit t('save'), class: 'btn btn-info'

app/views/admin/exams/edit.html.slim
= content_for :title, @exam.name

.page-heading
  .heading-accent
  h1
    = @exam.name

  .actions
    = link_to(t("back"), admin_exams_path, class: "btn btn-info")
    = link_to(t("delete"), admin_exam_path(@exam), class: "btn btn-danger", method: :delete, data: { confirm: t("confirm") })

= render 'form'

app/views/admin/exams/index.html.slim
= content_for :title, tc_few(Exam)

.page-heading
  .heading-accent
  h1 = tc_few(Exam)

  .actions
    = link_to t(".new_exam"), new_admin_exam_path, class: "btn btn-info"

table
  tr
    th = t("order")
    th = ta(Exam, :name)
    th = t("actions")

  - @exams.each_with_index do |exam, idx|
    tr
      td = idx + 1
      td = exam.name
      td = link_to t("edit"), edit_admin_exam_path(exam), class: "btn btn-info"

app/views/admin/exams/new.html.slim
= content_for :title, t(".title")

.page-heading
  .heading-accent
  h1 = t('.title')

  .actions
    = link_to(t("back"), admin_exams_path, class: "btn btn-info")

= render "form"