config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :exams
    resources :users
    resources :tasks
    resources :groups do
      resources :students, only: [:index, :create, :destroy] do
        put :update_number, on: :collection
      end
    end
  end

  namespace :exam do
    resources :groups
    resources :students do
      resources :tasks
    end
  end

  namespace :reports do
    resources :groups, only: [:index, :show]
  end

  resources :exams, only: [] do
    put :set_current, on: :member
  end

  root 'exam/groups#index'
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :students, through: :groups
  has_many :subtasks, through: :tasks

  validates :name, presence: true, uniqueness: true

  def to_s
    name
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  KINDS = %w{extended bilingual}

  belongs_to :exam
  has_and_belongs_to_many :teachers, class_name: User.name
  has_many :students, dependent: :destroy
  has_many :scores, through: :students
  has_many :tasks, through: :students

  accepts_nested_attributes_for :students

  scope :groups_for_select, -> { joins(:exam).order('exams.name', :name) }

  validates :name, presence: true, uniqueness: { scope: :exam }

  def students_number
    students.standard.count + students.extended.count + students.bilingual.count
  end

  def standard_tasks
    tasks.where(level: 'standard').order(:number, :secondary_number).distinct
  end

  def extended_tasks
    tasks.where(level: 'extended').order(:number, :secondary_number).distinct
  end

  def bilingual_tasks
    tasks.where(level: 'bilingual').order(:number, :secondary_number).distinct
  end

  def full_name
    "#{exam.name} - #{name}"
  end
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < Admin::BaseController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def create
    if @exam.save
      redirect_to admin_exams_path, notice: t('.exam_created')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @exam.update(exam_params)
      redirect_to edit_admin_exam_path(@exam), notice: t('.exam_updated')
    else
      render :edit
    end
  end

  def destroy
    @exam.destroy
    redirect_to admin_exams_path, notice: t('.exam_destroyed')
  end

  private

  def exam_params
    params.require(:exam).permit(:name)
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController
  load_and_authorize_resource through: :current_exam

  def index
  end

  def new
  end

  def create
    if @group.save
      redirect_to edit_admin_group_path(@group), notice: t('.group_created')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to edit_admin_group_path(@group), notice: t('.group_updated')
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to admin_groups_path, notice: t('.group_destroyed')
  end

  private

  def group_params
    params.require(:group).permit(:name, :kind)
  end
end

app/controllers/exam/base_controller.rb
class Exam::BaseController < BaseController
end

app/controllers/exam/groups_controller.rb
class Exam::GroupsController < Exam::BaseController
  load_and_authorize_resource through: :current_exam

  def index
  end

  def edit
  end

  def update
  end

  def show
    @tasks = @group.tasks
  end
end

app/controllers/exam/tasks_controller.rb
class Exam::TasksController < Exam::BaseController
  load_and_authorize_resource :student, through: :current_exam
  load_and_authorize_resource through: :student

  def edit
    @scores = @task.scores.where(student: @student).ordered
  end

  def update
    @scores = Score.update(params[:scores].keys, params[:scores].values)
    @scores.reject! { |s| s.errors.empty? }

    if @scores.empty?
      next_task = @student.tasks.where(level: @task.level).where('tasks.number > ?', @task.number).first || @student.tasks.where(level: @task.level).where('tasks.number >= ? AND tasks.secondary_number > ?', @task.number, @task.secondary_number).first
      
      if next_task
        redirect_to edit_exam_student_task_url(@student, next_task)
      else
        task_level = @task.level != 'standard' ? @task.level : nil
        redirect_to edit_exam_group_url(@student.group, group_type: task_level), notice: t('.score_updated')
      end
    else
      render :edit
    end
  end
end

app/controllers/exams_controller.rb
class ExamsController < BaseController
  load_and_authorize_resource

  def set_current
    set_current_exam(@exam.id)
    redirect_to root_path, notice: t('custom_messages.exam_changed', exam: @exam.name)
  end
end

app/controllers/reports/groups_controller.rb
class Reports::GroupsController < Reports::BaseController
  load_and_authorize_resource through: :current_exam

  def index
  end

  def show
    scores_reporter

    respond_to do |format|
      format.html
      format.xlsx do
        render xlsx: 'show', filename: "#{current_exam.name} - #{timestamp}"
      end
    end
  end

  private

  def scores_reporter
    @standard_scores_reporter ||= ScoresReporter.new @group, 'standard'
    @extended_scores_reporter ||= ScoresReporter.new @group, 'extended'
    @bilingual_scores_reporter ||= ScoresReporter.new @group, 'bilingual'
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
  def current_exam
    @current_exam ||= Exam.find_by(id: current_exam_id) || Exam.first
  end

  def set_current_exam(id)
    cookies.signed[:current_exam] = id
    # flash.notice = t('flash.custom.current_plant_set', exam: current_exam)
  end

  def current_exam_id
    if can? :set_current, Exam
      cookies.signed[:current_exam]
    else
      Exam.first.id
    end
  end

  def available_exams
    Exam.all
  end
end

app/views/exam/groups/edit.html.slim
= content_for :title, @group.name

.page-heading
  .heading-accent
  h1 = @group.name

  .actions
    = link_to t('back'), exam_groups_path, class: 'btn btn-info'

ul.accordion-tabs-minimal
  - if @group.standard_tasks.any?
    li.tab-header-and-content#standard
      a.tab-link.is-active{:href => "#"} = t('task.levels.standard')
      .tab-content
        table.fixed-table
          tr
            th.wider-cell
              - skills_heading(@group.standard_tasks)
            th = t('total')

          tr
            th.wider-cell = tc(Student)

            - @group.standard_tasks.each do |task|
              th = task.extended_number
            th

          - @group.students.standard.each do |student|
            tr
              td = link_to student.name, edit_exam_student_task_path(student, student.standard_tasks.first)
              - student.standard_tasks.each do |task|
                td = link_to task.full_score(student), edit_exam_student_task_path(student, task)

              td = student.total_for_all_tasks('standard')

  - if @group.extended_tasks.any?
    li.tab-header-and-content#extended
      a.tab-link{:href => "#"} = t('task.levels.extended')
      .tab-content
        table.fixed-table
          tr
            th.wider-cell
              - skills_heading(@group.extended_tasks)
            th= t('total')

          tr
            th.wider-cell = tc(Student)

            - @group.extended_tasks.each do |task|
              th = task.extended_number
            th

          - @group.students.extended.each do |student|
            tr
              td = link_to student.name, edit_exam_student_task_path(student, student.extended_tasks.first)
              - student.extended_tasks.each do |task|
                td = link_to task.full_score(student), edit_exam_student_task_path(student, task)

              td = student.total_for_all_tasks('extended')

  - if @group.bilingual_tasks.any?
    li.tab-header-and-content#bilingual
      a.tab-link{:href => "#"} = t('task.levels.bilingual')
      .tab-content
        table.fixed-table
          tr
            th.wider-cell
              - skills_heading(@group.bilingual_tasks)
            th= t('total')

          tr
            th.wider-cell = tc(Student)

            - @group.bilingual_tasks.each do |task|
              th = task.extended_number
            th

          - @group.students.bilingual.each do |student|
            tr
              td = link_to student.name, edit_exam_student_task_path(student, student.bilingual_tasks.first)
              - student.bilingual_tasks.each do |task|
                td = link_to task.full_score(student), edit_exam_student_task_path(student, task)

              td = student.total_for_all_tasks('bilingual')

app/views/exam/groups/index.html.slim
= content_for :title, t('.title')

.page-heading
  .heading-accent
  h1 = t('.title')

  .actions

table
  tr
    th = t('order')
    th = ta(Group, :name)
    th = t('actions')

  - @groups.each_with_index do |group, idx|
    tr
      td = idx + 1
      td = group.name
      td = link_to t('.enter_scores'), edit_exam_group_path(group), class: 'btn btn-info'

app/views/exam/groups/show.html.slim
= content_for :title, @group.name

h2 = @group.name

ul.accordion-tabs-minimal
  - if @group.standard_tasks.any?
    li.tab-header-and-content
      a.tab-link.is-active{:href => "#"} = t('tasks.levels.standard')
      .tab-content
        table
          tr
            th = tc(Student)

            - @tasks.standard.uniq.each do |task|
              th = task.number

          - @group.students.each do |student|
            tr
              td = student.name
              - student.tasks.standard.uniq.each do |task|
                td = student.sum_scores_by_task(task.id)


  li.tab-header-and-content
    - if @group.extended_tasks.any?
      a.tab-link{:href => "#"} = t('tasks.levels.extended')
      .tab-content
        table
          tr
            th = tc(Student)

            - @tasks.extended.uniq.each do |task|
              th= task.number

          - @group.students.each do |student|
            tr
              td = student.name
              - student.tasks.extended.uniq.each do |task|
                td = student.sum_scores_by_task(task.id)

  li.tab-header-and-content
    - if @group.bilingual_tasks.any?
      a.tab-link{:href => "#"} = t('tasks.levels.bilingual')
      .tab-content
        table
          tr
            th = tc(Student)

            - @tasks.bilingual.uniq.each do |task|
              th = task.number

          - @group.students.each do |student|
            tr
              td = student.name
              - student.tasks.bilingual.uniq.each do |task|
                td = student.sum_scores_by_task(task.id)