config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :exams
    resources :users
    resources :tasks
    resources :groups do
      resources :students, only: [:index, :create, :destroy] do
        put :update_number, on: :collection
      end
    end
  end

  namespace :exam do
    resources :groups
    resources :students do
      resources :tasks
    end
  end

  namespace :reports do
    resources :groups, only: [:index, :show]
  end

  resources :exams, only: [] do
    put :set_current, on: :member
  end

  root 'exam/groups#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
  KINDS = %w{extended bilingual}

  belongs_to :exam
  has_and_belongs_to_many :teachers, class_name: User.name
  has_many :students, dependent: :destroy
  has_many :scores, through: :students
  has_many :tasks, through: :students

  accepts_nested_attributes_for :students

  scope :groups_for_select, -> { joins(:exam).order('exams.name', :name) }

  validates :name, presence: true, uniqueness: { scope: :exam }

  def students_number
    students.standard.count + students.extended.count + students.bilingual.count
  end

  def standard_tasks
    tasks.where(level: 'standard').order(:number, :secondary_number).distinct
  end

  def extended_tasks
    tasks.where(level: 'extended').order(:number, :secondary_number).distinct
  end

  def bilingual_tasks
    tasks.where(level: 'bilingual').order(:number, :secondary_number).distinct
  end

  def full_name
    "#{exam.name} - #{name}"
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController
  load_and_authorize_resource through: :current_exam

  def index
  end

  def new
  end

  def create
    if @group.save
      redirect_to edit_admin_group_path(@group), notice: t('.group_created')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to edit_admin_group_path(@group), notice: t('.group_updated')
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to admin_groups_path, notice: t('.group_destroyed')
  end

  private

  def group_params
    params.require(:group).permit(:name, :kind)
  end
end

app/controllers/exam/groups_controller.rb
class Exam::GroupsController < Exam::BaseController
  load_and_authorize_resource through: :current_exam

  def index
  end

  def edit
  end

  def update
  end

  def show
    @tasks = @group.tasks
  end
end

app/controllers/reports/groups_controller.rb
class Reports::GroupsController < Reports::BaseController
  load_and_authorize_resource through: :current_exam

  def index
  end

  def show
    scores_reporter

    respond_to do |format|
      format.html
      format.xlsx do
        render xlsx: 'show', filename: "#{current_exam.name} - #{timestamp}"
      end
    end
  end

  private

  def scores_reporter
    @standard_scores_reporter ||= ScoresReporter.new @group, 'standard'
    @extended_scores_reporter ||= ScoresReporter.new @group, 'extended'
    @bilingual_scores_reporter ||= ScoresReporter.new @group, 'bilingual'
  end
end

app/views/admin/groups/_form.html.haml
.row
  .col-6
    = simple_form_for [:admin, @group] do |f|
      = f.input :name

      = f.submit t('save'), class: 'btn btn-info'

app/views/admin/groups/_form.html.slim
.row
  .col-6
    = simple_form_for [:admin, @group] do |f|
      = f.input :name

      = f.submit t('save'), class: 'btn btn-info'

app/views/admin/groups/edit.html.slim
= content_for :title, @group.name

.page-heading
  .heading-accent
  h1 = @group.name

  .actions
    = link_to(t("back"), admin_groups_path, class: "btn btn-info")
    = link_to(t("delete"), admin_group_path(@group), class: "btn btn-danger", method: :destroy, data: { confirm: t("confirm") })

.row
  p
    = "#{t('.number_of_students')}: #{@group.students_number}"
    = link_to(t('.add_students'), admin_group_students_path(@group), class: "btn btn-info")

= render "form"

app/views/admin/groups/index.html.slim
= content_for :title, t('.title')

.page-heading
  .heading-accent
  h1 = t('.title')

  .actions
    = link_to t('.new_group'), new_admin_group_path, class: "btn btn-info"

.col-8
  table
    tr
      th = t("order")
      th = ta(Group, :name)
      th = t(".number_of_students")
      th = t("actions")

    - @groups.each_with_index do |group, idx|
      tr
        td = idx + 1
        td = group.name
        td = group.students_number
        td
          = link_to t("edit"), edit_admin_group_path(group), class: "btn btn-info"
          = link_to t(".view_students"), admin_group_students_path(group), class: "btn btn-info"
          = link_to t("delete"), admin_group_path(group), class: "btn btn-danger", method: :delete, data: { confirm: t("confirm") }

app/views/admin/groups/new.html.slim
= content_for :title, t(".title")

.page-heading
  .heading-accent
  h1 = t(".title")

  .actions
    = link_to t("back"), admin_groups_path, class: "btn btn-info"

= render "form"