config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :exams
    resources :users
    resources :tasks
    resources :groups do
      resources :students, only: [:index, :create, :destroy] do
        put :update_number, on: :collection
      end
    end
  end

  namespace :exam do
    resources :groups
    resources :students do
      resources :tasks
    end
  end

  namespace :reports do
    resources :groups, only: [:index, :show]
  end

  resources :exams, only: [] do
    put :set_current, on: :member
  end

  root 'exam/groups#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, 
    authentication_keys: [:login]

  ROLES = %w(admin teacher)

  has_and_belongs_to_many :groups
  has_many :filters, class_name: UserFilter.name, inverse_of: :user, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9_\.]*\z/ }
  validates :first_name, :last_name, presence: true

  def has_role?(role)
    self.role == role.to_s
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_hash).first
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def create
    if @user.save
      redirect_to edit_admin_user_path(@user), notice: t('.user_created')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to edit_admin_user_path(@user), notice: t('.user_updated')
    else
      render :edit
    end
  end

  private

  def user_params
    allow_empty_password
    params.require(:user).permit(:username, :first_name, :last_name, :password, :password_confirmation, :email, :role, group_ids: [])
  end

  def allow_empty_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end
end

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, @user] do |f|
  .row
    .col-6
      = f.input :username
      = f.input :email
      = f.input :password
      = f.input :password_confirmation

    .col-6.col-last
      = f.input :first_name
      = f.input :last_name
      = f.input :role, collection: User::ROLES
      = f.association :groups, collection: groups_for_select

  .row
    .col-12
      = f.submit t('save'), class: 'btn btn-info'

app/views/admin/users/_form.html.slim
= simple_form_for [:admin, @user] do |f|
  .row
    .col-6
      = f.input :username
      = f.input :email
      = f.input :password
      = f.input :password_confirmation

    .col-6.col-last
      = f.input :first_name
      = f.input :last_name
      = f.input :role, collection: User::ROLES
      = f.association :groups, collection: groups_for_select

  .row
    .col-12
      = f.submit t('save'), class: 'btn btn-info'

app/views/admin/users/edit.html.slim
= content_for :title, @user.username

.page-heading
  .heading-accent
  h1 = @user.username

  .actions
    = link_to t('back'), admin_users_path, class: 'btn btn-info'
    = link_to t('delete'), admin_user_path(@user), class: 'btn btn-danger', method: :delete, data: { confirm: t('confirm') }

= render 'form'

app/views/admin/users/index.html.slim
= content_for :title, tc_few(User)

.page-heading
  .heading-accent
  h1 = tc_few(User)

  .actions
    = link_to t('.new_user'), new_admin_user_path, class: 'btn btn-info'

.users-list
  table
    tr
      th = t('order')
      th = ta(User, :username)
      th = ta(User, :first_name)
      th = ta(User, :last_name)
      th = ta(User, :email)
      th = ta(User, :role)
      th = t('actions')

    - @users.each_with_index do |user, idx|
      tr
        td = idx + 1
        td = user.username
        td = user.first_name
        td = user.last_name
        td = user.email
        td = user.role
        td = link_to t('edit'), edit_admin_user_path(user), class: 'btn btn-info'

app/views/admin/users/new.html.slim
= content_for :title, t('.new_user')

.page-heading
  .heading-accent
  h1 = t('.new_user')

  .actions
    = link_to t('back'), admin_users_path, class: 'btn btn-info'

= render 'form'